image: node:18

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run build -- --configuration production --base-href="/$CI_PROJECT_NAME/"
    - mkdir -p public
    - cp -r dist/*/. public/
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - develop
